version: "3.8"
services:
  react-app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev #development
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    environment:
      - NODE_ENV=development
      - VITE_PROJECT_NAME=ifocorporation
      - WATCHPACK_POLLING=true
    env_file:
      - .env
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app
