version: "3.8"
services:
  react-app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    restart: always
    environment:
      - VITE_PROJECT_NAME=ifocorporation
      - WATCHPACK_POLLING=true
    env_file:
      - .env

