# Base image
FROM node:16.14.0-alpine AS develop

RUN apk add --no-cache libc6-compat

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile --non-interactive --cache-folder ./ycache

# Copy all files to the container
COPY . .

# Expose port 3000 for development
EXPOSE 3000

# Start the app in development mode
CMD ["yarn", "dev"]

# Base image Nginx
FROM nginx

# Copy nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy files from dist directory to the nginx/html
COPY --from=develop /app /usr/share/nginx/html
