name: QA Testing Environment

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package.json
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build --if-present
      - name: Run tests
        run: npm run test
